const mongoose = require("mongoose");
const User = require("../models/User"); // Adjust the path as necessary
require("dotenv").config();

const userData = [
  {
    name: "Alice Smith",
    email: "alice@example.com",
    password: "password123",
    phoneNumber: "123-456-7890",
    hasAnsweredQuestions: true,
    responses: {
      age: "28",
      occupation: "Engineer",
      monthlyIncome: "70000",
      monthlyExpenses: "30000",
      marketExperience: "2",
      investmentProfile: "Aggressive",
      portfolioSize: "20-50L",
      investmentGoal: "x10In10Years",
      knowledgeSource: ["Blogs", "Forums"],
      tradingSource: "No",
      follow: ["John Doe"],
      idol: "Warren Buffett",
      primaryGoal: ["retirement"],
      investmentHorizon: "shortTerm",
      portfolioReview: "quarterly",
      timeSpent: "1 hour",
      currentHoldings: ["Tech", "Healthcare"],
      sectorPreferences: ["technology", "healthcare"],
      sectorAvoid: "energy",
      investmentRestrictions: "No defense stocks",
      portfolioAllocation: {
        swingTrading: "10",
        positionalShort: "20",
        longPositions: "40",
        investment: "25",
        emergencyFund: "5",
      },
      specificScrips: "AAPL, GOOGL",
      investmentStrategy: "Growth Investing",
      recommendations: ["buy", "hold"],
      updateFrequency: "monthly",
      advisoryPreference: "automated",
      existingInvestments: "ETFs, Bonds",
      incorporateInvestments: "no",
      specificGoals: "Buy a new car",
      additionalNotes: "Looking for high-growth opportunities.",
    },
  },
  {
    name: "Bob Johnson",
    email: "bob@example.com",
    password: "securepassword",
    phoneNumber: "987-654-3210",
    hasAnsweredQuestions: false,
    responses: {
      age: null,
      occupation: null,
      monthlyIncome: null,
      monthlyExpenses: null,
      marketExperience: null,
      investmentProfile: null,
      portfolioSize: null,
      investmentGoal: null,
      knowledgeSource: null,
      tradingSource: null,
      follow: null,
      idol: null,
      primaryGoal: null,
      investmentHorizon: null,
      portfolioReview: null,
      timeSpent: null,
      currentHoldings: null,
      sectorPreferences: null,
      sectorAvoid: null,
      investmentRestrictions: null,
      portfolioAllocation: {
        swingTrading: null,
        positionalShort: null,
        longPositions: null,
        investment: null,
        emergencyFund: null,
      },
      specificScrips: null,
      investmentStrategy: null,
      recommendations: null,
      updateFrequency: null,
      advisoryPreference: null,
      existingInvestments: null,
      incorporateInvestments: null,
      specificGoals: null,
      additionalNotes: null,
    },
  },
  {
    name: "Charlie Davis",
    email: "charlie@example.com",
    password: "mypassword",
    phoneNumber: "555-666-7777",
    hasAnsweredQuestions: true,
    responses: {
      age: "40",
      occupation: "Teacher",
      monthlyIncome: "50000",
      monthlyExpenses: "20000",
      marketExperience: "10",
      investmentProfile: "Conservative",
      portfolioSize: "50L-1C",
      investmentGoal: "double1Year",
      knowledgeSource: ["Books", "Seminars"],
      tradingSource: "Yes",
      follow: ["Jane Doe"],
      idol: "Peter Lynch",
      primaryGoal: ["childrenEducation"],
      investmentHorizon: "mediumTerm",
      portfolioReview: "biannually",
      timeSpent: "30 minutes",
      currentHoldings: ["Real Estate", "Utilities"],
      sectorPreferences: ["real estate", "utilities"],
      sectorAvoid: "tech",
      investmentRestrictions: "No gambling stocks",
      portfolioAllocation: {
        swingTrading: "5",
        positionalShort: "10",
        longPositions: "60",
        investment: "20",
        emergencyFund: "5",
      },
      specificScrips: "TSLA, AMZN",
      investmentStrategy: "Index Investing",
      recommendations: ["sell", "hold"],
      updateFrequency: "annually",
      advisoryPreference: "personal",
      existingInvestments: "Savings Accounts",
      incorporateInvestments: "yes",
      specificGoals: "Vacation Fund",
      additionalNotes: "Focus on stable investments.",
    },
  },
  {
    name: "Dana White",
    email: "dana@example.com",
    password: "password789",
    phoneNumber: "222-333-4444",
    hasAnsweredQuestions: true,
    responses: {
      age: "32",
      occupation: "Designer",
      monthlyIncome: "80000",
      monthlyExpenses: "40000",
      marketExperience: "6",
      investmentProfile: "Moderate",
      portfolioSize: "10-25L",
      investmentGoal: "x10In10Years",
      knowledgeSource: ["YouTube", "Groups"],
      tradingSource: "No",
      follow: ["Steve Jobs"],
      idol: "Elon Musk",
      primaryGoal: ["futureWealth"],
      investmentHorizon: "longTerm",
      portfolioReview: "monthly",
      timeSpent: "3 hours",
      currentHoldings: ["Finance", "Energy"],
      sectorPreferences: ["finance", "energy"],
      sectorAvoid: "pharmaceuticals",
      investmentRestrictions: "No unethical companies",
      portfolioAllocation: {
        swingTrading: "25",
        positionalShort: "25",
        longPositions: "25",
        investment: "15",
        emergencyFund: "10",
      },
      specificScrips: "MSFT, NFLX",
      investmentStrategy: "Value Investing",
      recommendations: ["buy", "hold"],
      updateFrequency: "quarterly",
      advisoryPreference: "automated",
      existingInvestments: "Gold, Silver",
      incorporateInvestments: "yes",
      specificGoals: "Build a house",
      additionalNotes: "Interested in sustainable investments.",
    },
  },
  {
    name: "Eve Brown",
    email: "eve@example.com",
    password: "evepassword",
    phoneNumber: "999-888-7777",
    hasAnsweredQuestions: true,
    responses: {
      age: "29",
      occupation: "Accountant",
      monthlyIncome: "90000",
      monthlyExpenses: "35000",
      marketExperience: "3",
      investmentProfile: "Conservative",
      portfolioSize: "25-50L",
      investmentGoal: "double1Year",
      knowledgeSource: ["Webinars", "Podcasts"],
      tradingSource: "Yes",
      follow: ["Robert Kiyosaki"],
      idol: "Benjamin Graham",
      primaryGoal: ["retirement"],
      investmentHorizon: "shortTerm",
      portfolioReview: "weekly",
      timeSpent: "4 hours",
      currentHoldings: ["Healthcare", "Tech"],
      sectorPreferences: ["healthcare", "tech"],
      sectorAvoid: "real estate",
      investmentRestrictions: "No sin stocks",
      portfolioAllocation: {
        swingTrading: "15",
        positionalShort: "20",
        longPositions: "50",
        investment: "10",
        emergencyFund: "5",
      },
      specificScrips: "NVDA, FB",
      investmentStrategy: "Growth Investing",
      recommendations: ["buy", "hold"],
      updateFrequency: "monthly",
      advisoryPreference: "personal",
      existingInvestments: "Mutual Funds, ETFs",
      incorporateInvestments: "no",
      specificGoals: "Early Retirement",
      additionalNotes: "Looking for tax-efficient investments.",
    },
  },
];

const seedUsers = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    // console.log("Connected to MongoDB");

    // Delete existing users to avoid duplicates
    await User.deleteMany({});

    // Insert new user data
    for (const user of userData) {
      const newUser = new User(user);
      await newUser.save();
    }

    // console.log("Users seeded successfully");
    mongoose.disconnect();
  } catch (error) {
    console.error("Error seeding users:", error);
    mongoose.disconnect();
  }
};

seedUsers();
